name: Build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build -t redkrane/skyprogram:$GITHUB_REF_NAME-$GITHUB_RUN-ID .
      - name: login
        run: docker login -u ${{ DOCKER_USERNAME }} -p ${{ DOCKER_TOKEN }}
      - name: push
        run: docker push redkrane/skyprogram:$GITHUB_REF_NAME-$GITHUB_RUN-ID
