name: Build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build -t redkrane/skyprogram:$GITHUB_REF_NAME-$GITHUB_RUN-ID .
      - name: login
        run: echo ${{ DOCKER_TOKEN }} | docker login -u ${{ DOCKER_USERNAME }} --password-stdin
      - name: push
        run: docker push redkrane/skyprogram:$GITHUB_REF_NAME-$GITHUB_RUN-ID
